### ISSUE TITLE
mix ecto.create fails

### ISSUE THREAD

**Issue by yix** [jimm/expensive#1]
Hello, I'm trying to run setup the app but getting following error when executing `mix ecto.create`. `web/router.ex` is there but for some reason it
[mix_ecto.create.txt](https://github.com/jimm/expensive/files/72771/mix_ecto.create.txt)
 is not hooked up properly.

```
== Compilation error on file lib/expensive/endpoint.ex ==
** (UndefinedFunctionError) undefined function: Expensive.Router.init/1 (module Expensive.Router is not available)
```

Thanks.

**Comment by jimm** [comment]
@yix, I'm very sorry that I didn't see this issue until now. This project is just a little one that I was using to learn Phoenix. It's horribly out of date, and I haven't kept it up with the changes to Ecto or Phoenix.

I don't plan to updated this project, though if I do then I'll certainly check in any fixes here.

I hope you figured out the problem. Best of luck to you.
